export const webComponentNames = {
    Avatar: 'Avatar',
    AvatarWithStatus: 'AvatarWithStatus',
    Badge: 'Badge',
    Box: 'Box',
    Button: 'Button',
    Checkbox: 'Checkbox',
    Chip: 'Chip',
    Chips: 'Chips',
    FieldButton: 'FieldButton',
    FieldLayout: 'FieldLayout',
    FieldAdditionalText: 'FieldAdditionalText',
    Heading: 'Heading',
    Icon: 'Icon',
    IconButton: 'IconButton',
    InputDate: 'InputDate',
    InputNumber: 'InputNumber',
    InputPassword: 'InputPassword',
    InputText: 'InputText',
    InputTime: 'InputTime',
    LayoutFlex: 'LayoutFlex',
    LayoutFlexItem: 'LayoutFlexItem',
    LayoutGrid: 'LayoutGrid',
    LayoutGridItem: 'LayoutGridItem',
    Link: 'Link',
    Loader: 'Loader',
    NumberField: 'NumberField',
    ObserverIntersection: 'ObserverIntersection',
    Panel: 'Panel',
    PanelBody: 'PanelBody',
    PanelFooter: 'PanelFooter',
    PanelHeader: 'PanelHeader',
    PanelSection: 'PanelSection',
    PasswordField: 'PasswordField',
    PreplyLogo: 'PreplyLogo',
    Radio: 'Radio',
    Select: 'Select',
    SelectField: 'SelectField',
    SelectFieldOption: 'SelectFieldOption',
    SelectFieldLayout: 'SelectFieldLayout',
    Text: 'Text',
    Textarea: 'Textarea',
    TextareaField: 'TextareaField',
    TextField: 'TextField',
    TextHighlighted: 'TextHighlighted',
    TextInline: 'TextInline',

    // Hard-coded in SVGs
    SvgIcon: 'SvgIcon',
    SvgTokyoUIIcon: 'SvgTokyoUIIcon',
    SvgTokyoUIIllustration: 'SvgTokyoUIIllustration',
} as const;

export const appComponentNames = {
    Button: 'Button',
    Heading: 'Heading',
    LayoutFlex: 'LayoutFlex',
    LayoutFlexItem: 'LayoutFlexItem',
    Text: 'Text',
    TextInline: 'TextInline',
    Loader: 'Loader',

    // Hard-coded in SVGs
    SvgIcon: 'SvgIcon',
    SvgTokyoUIIcon: 'SvgTokyoUIIcon',
    SvgTokyoUIIllustration: 'SvgTokyoUIIllustration',
} as const;

export const rebrandComponentNames = {
    RebrandAccordion: 'RebrandAccordion',
    RebrandAlert: 'RebrandAlert',
    RebrandBubble: 'RebrandBubble',
    RebrandBubbleOnIcon: 'RebrandBubbleOnIcon',
    RebrandCheckbox: 'RebrandCheckbox',
    RebrandChip: 'RebrandChip',
    RebrandChoiceTile: 'RebrandChoiceTile',
    RebrandDivider: 'RebrandDivider',
    RebrandDropdown: 'RebrandDropdown',
    RebrandFlag: 'RebrandFlag',
    RebrandListItem: 'RebrandListItem',
    RebrandListMenu: 'RebrandListMenu',
    RebrandModal: 'RebrandModal',
    RebrandPopover: 'RebrandPopover',
    RebrandProgressBar: 'RebrandProgressBar',
    RebrandRadioButton: 'RebrandRadioButton',
    RebrandRadioGroup: 'RebrandRadioGroup',
    RebrandRange: 'RebrandRange',
    RebrandRating: 'RebrandRating',
    RebrandSegmentedButtons: 'RebrandSegmentedButtons',
    RebrandSegmentedControls: 'RebrandSegmentedControls',
    RebrandSelect: 'RebrandSelect',
    RebrandSlider: 'RebrandSlider',
    RebrandStackedImage: 'RebrandStackedImage',
    RebrandSwitch: 'RebrandSwitch',
    RebrandTabs: 'RebrandTabs',
    RebrandToast: 'RebrandToast',
    RebrandTooltip: 'RebrandTooltip',
} as const;

export const dsCandidateComponentNames = {
    DsCandidateAlert: 'DsCandidateAlert',
    DsCandidateAvatar: 'DsCandidateAvatar',
    DsCandidateAvatarWithStatus: 'DsCandidateAvatarWithStatus',
    DsCandidateBadge: 'DsCandidateBadge',
    DsCandidateBox: 'DsCandidateBox',
    DsCandidateBubble: 'DsCandidateBubble',
    DsCandidateCheckbox: 'DsCandidateCheckbox',
    DsCandidateChip: 'DsCandidateChip',
    DsCandidateChoiceTile: 'DsCandidateChoiceTile',
    DsCandidateCollapsibleList: 'DsCandidateCollapsibleList',
    DsCandidateCollapsibleItem: 'DsCandidateCollapsibleItem',
    DsCandidateDivider: 'DsCandidateDivider',
    DsCandidateFlag: 'DsCandidateFlag',
    DsCandidateFullScreenLayoutAccent: 'DsCandidateFullScreenLayoutAccent',
    DsCandidateIcon: 'DsCandidateIcon',
    DsCandidateIconFlat: 'DsCandidateIconFlat',
    DsCandidateIconFlatWithStyle: 'DsCandidateIconFlatWithStyle',
    DsCandidateIconButton: 'DsCandidateIconButton',
    DsCandidateLink: 'DsCandidateLink',
    DsCandidateListItem: 'DsCandidateListItem',
    DsCandidateProgressBar: 'DsCandidateProgressBar',
    DsCandidateRadio: 'DsCandidateRadio',
    DsCandidateRating: 'DsCandidateRating',
    DsCandidateRatingStar: 'DsCandidateRatingStar',
    DsCandidateSegmentedControlActiveOption: 'DsCandidateSegmentedControlActiveOption',
    DsCandidateSegmentedControl: 'DsCandidateSegmentedControl',
    DsCandidateSlider: 'DsCandidateSlider',
    DsCandidateStackedButton: 'DsCandidateStackedButton',
    DsCandidateSwitch: 'DsCandidateSwitch',
    DsCandidateTab: 'DsCandidateTab',
    DsCandidateTabs: 'DsCandidateTabs',
    DsCandidateTextArea: 'DsCandidateTextArea',
    DsCandidateTextField: 'DsCandidateTextField',
    DsCandidateTooltip: 'DsCandidateTooltip',
} as const;
