name: Production
on:
    pull_request:
        types:
            - closed
        branches:
            - main
jobs:
    ProductionDeploy:
        timeout-minutes: 15
        if: github.event.pull_request.merged == true
        env:
            AWS_REGION: eu-west-1
            RAVEN_ENVIRONMENT: PROD
            NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
            PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        permissions:
            contents: read # This is required for actions/checkout
            id-token: write # This is required for requesting the JWT
            pull-requests: write # This is required for actions-comment-pull-request
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  role-to-assume: arn:aws:iam::537716077656:role/github-actions
                  role-session-name: deploy-ds-storybook-prod
                  aws-region: ${{ env.AWS_REGION }}
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc
                  cache: yarn
            - name: Install dependencies
              run: yarn install --immutable
            - name: Lint
              run: yarn lint
            - name: Build
              run: yarn build
            - name: Install Playwright
              run: npx playwright install chromium
            - name: Test
              run: yarn test
            - name: Test RSC
              run: |
                cd examples/next-js
                yarn
                yarn build
                cd -
            - name: Publish to NPM
              run: |
                  npm whoami
                  yarn publish:current
            - name: Deploy static assets
              run: scripts/deploy-static-assets.sh
            - name: Deploy storybook
              run: scripts/deploy-storybook.sh
            - name: On Success
              if: success()
              uses: thollander/actions-comment-pull-request@v2
              with:
                  comment_tag: success_comment
                  mode: recreate
                  message: |
                      Production storybook has been deployed :rocket:

                      https://ds.preply.org/
            - name: On Failure
              if: failure()
              uses: thollander/actions-comment-pull-request@v2
              with:
                  comment_tag: failure_comment
                  mode: recreate
                  message: |
                      Production deployment failed :scream:
