name: Staging
on:
  - pull_request
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  # 'StagingDeploy' is used in branch ruleset as a required check
  # If you're going to change the name, make sure to update the branch ruleset
  StagingDeploy:
    timeout-minutes: 15
    env:
      AWS_REGION: us-east-1
      PR_NUMBER: ${{ github.event.pull_request.number }}
      RAVEN_ENVIRONMENT: STAGE
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    permissions:
      contents: read    # This is required for actions/checkout
      id-token: write   # This is required for requesting the JWT
      pull-requests: write # This is required for actions-comment-pull-request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::789264700756:role/github-actions
          role-session-name: deploy-ds-storybook-pr
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Install Playwright
        run: npx playwright install chromium
      - name: Test
        run: yarn test
      - name: Deploy static assets
        run: scripts/deploy-static-assets.sh
      - name: Deploy storybook
        run: scripts/deploy-storybook.sh
      - name: Deploy preview packages
        run: npx pkg-pr-new publish $(ls -d ./packages/*) --template './examples/*'
        continue-on-error: true
      # This should go after pkg-pr-new publish to prevent it from failing
      - name: Test RSC
        run: |
          cd examples/next-js
          yarn
          yarn build
          cd -
      - name: On Success
        if: success()
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: success_comment
          mode: recreate
          message: |
            Storybook has been published for testing :rocket:

            https://ds.staging.preply.org/${{ github.event.pull_request.number }}
      - name: On Failure
        if: failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: failure_comment
          mode: recreate
          message: |
            Staging deployment failed :sob:

